  version: "3"
  
  services:  
    backend:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 8000:8000
      tty: true
      volumes: 
        - .dockervenv:/src/.venv
        - .:/src